services:
  civicpatch-cicd:
    environment:
      - GOOGLE_GEMINI_TOKEN
      - TOGETHER_AI_TOKEN

      - CIVICPATCH_ORG_URL
      - SERVICE_API_KEY

      - JOB_RUN_URL

      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - APP_ROOT=/app
    init: true # https://stackoverflow.com/questions/50634819/xvfb-run-hangs-in-container
    image: ghcr.io/civicpatch/civicpatch-github-actions:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile.github-actions
    #network_mode: host
    volumes:
      - ./data:/app/data
      - ./data_source:/app/data_source
