name: "[api] - Data Scrape"

on:
  workflow_dispatch:
    inputs:
      jurisdiction_ocdid:
        description: "ocdid for the municipality (e.g. ocd-division/country/state/city)"
        required: true
      name:
        description: 'E.g. "Greensboro city"'
        required: false
      url:
        description: "URL of the city council page"
        required: false
      request_id:
        description: "If invoking via API, request_id is required to track jobs"
        required: false
      source_urls:
        description: "JSON array of specific URLs to scrape (e.g. [\"https://...\"])"
        required: false
      mode:
        description: "Run mode: 'start' (default) or 'resume'"
        required: false
        default: "start"

jobs:
  data-scrape:
    timeout-minutes: 30
    environment: env-${{ github.actor }}

    runs-on: ubuntu-latest

    steps:
      - name: Request ${{ inputs.request_id }}
        run: echo "request_id=${{ inputs.request_id }}"

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Setup mise
        uses: jdx/mise-action@v3.2.0
        with:
          version: "2025.9.6"
          cache: true
          log_level: debug
          github_token: ${{ secrets.GITHUB_TOKEN }}

      #uses: ScribeMD/docker-cache@0.5.0
      #with:
      #  key: docker-${{ steps.get-date.outputs.date }}

      - name: Pull docker image
        run: |
          docker compose pull
          docker images

      - name: Run data scrape
        env:
          CIVICPATCH_ORG_URL: https://civicpatch.org
          SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY }}
          JOB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          GOOGLE_GEMINI_TOKEN: ${{ secrets.GOOGLE_GEMINI_TOKEN }}
          OPEN_ROUTER_TOKEN: ${{ secrets.OPEN_ROUTER_TOKEN }}
          SOURCE_URLS: ${{ github.event.inputs.source_urls }}
        run: |
          echo "Job run URL: $JOB_RUN_URL"
          docker compose run --rm civicpatch-cicd python src/interfaces/cli/main.py \
                run_pipeline \
                --jurisdiction-ocdid "${{ github.event.inputs.jurisdiction_ocdid }}" \
                --name "${{ github.event.inputs.name }}" \
                --url "${{ github.event.inputs.url }}" \
                --request-id "${{ github.event.inputs.request_id }}" \
                --source-urls "$SOURCE_URLS" \
                --mode "${{ github.event.inputs.mode }}"
