name: "[manual] - Data Scrape by Population"

on:
  workflow_dispatch:
    inputs:
      state:
        description: "State initials (e.g. co, wa)"
        required: true
        type: choice
        options:
          - co
          - mi
          - nj
          - wa
          - tx
      num_jurisdictions:
        description: "Number of jurisdictions to scrape"
        required: false
        default: "10"
        type: string

jobs:
  fetch-jurisdictions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    timeout-minutes: 5
    steps:
      - name: Get scrape candidates
        id: set-matrix
        env:
          SERVICE_API_KEY: ${{ secrets.SERVICE_API_KEY }}
          CIVICPATCH_ORG_URL: https://civicpatch.org
        run: |
          RESPONSE=$(curl -s --fail-with-body \
            "${CIVICPATCH_ORG_URL}/api/v1/jurisdictions/available?state=${{ github.event.inputs.state }}&num_jurisdictions=${{ github.event.inputs.num_jurisdictions }}" \
            -H "Authorization: ${SERVICE_API_KEY}")
          echo "matrix=$(echo "$RESPONSE" | jq -c '.jurisdictions')" >> $GITHUB_OUTPUT

  scrape:
    needs: fetch-jurisdictions
    strategy:
      matrix:
        jurisdiction: ${{ fromJson(needs.fetch-jurisdictions.outputs.matrix) }}
      fail-fast: false
    uses: ./.github/workflows/data_scrape.yml
    with:
      jurisdiction_ocdid: ${{ matrix.jurisdiction.id }}
    secrets: inherit
